local fzf = require("fzf-lua")
vim.keymap.set("n", "<leader>f", fzf.files, {})
vim.keymap.set("n", "<leader>g", fzf.grep, {})
vim.keymap.set("n", "<leader>G", fzf.grep_last, {})
vim.keymap.set("n", "<leader>h", fzf.oldfiles, {})
vim.keymap.set("n", "<leader>b", fzf.buffers, {})
